In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load the CSV file
df = pd.read_csv('Vehiculos.csv')

print("Original shape:", df.shape)
print("\nFirst few rows:")
print(df.head())
print("\nLast few rows (to identify footer rows):")
print(df.tail())

Original shape: (30, 18)

First few rows:
    año  column2  Automóvilesa  Autobuses    Jeep   Carga  Motocicletas  \
0  2000  1631006        511171      47806   79676  231306        728964
1  2001  1689875        524980      49174   92374  241245        748543
2  2002  1754612        537272      52396  103000  251786        774951
3  2003  1804346        545275      55176  109008  259484        799154
4  2004  1827873        547291      55328  111260  261281        816298

   Volteo  Máquinas_Pesadas  Otrosb  Automóvilesa2  Autobuses2  Jeep2  Carga2  \
0   10817             12066    9200             31         2.9    4.9    14.2
1   11389             12664    9506             31         2.9    5.5    14.3
2   12187             13201    9819             30         3.0    5.9    14.3
3   12859             13380   10010             30         3.1    6.0    14.4
4   12871             13445   10099             29         3.0    6.1    14.3

   Motocicletas2  Volteo2  Máquinas_Pesadas2  Otrosb2
0      44.700001      0.7                0.7      0.6
1      44.299999      0.7                0.7      0.6
2      44.200001      0.7                0.8      0.6
3      44.299999      0.7                0.7      0.6
4      44.700001      0.7                0.7      0.6

Last few rows (to identify footer rows):
                                                  año  column2  Automóvilesa  \
25                     *Cifras sujetas a rectifiación        0       1157870
26  Nota: El parque vehicular se refiere al stock ...        0       1157870
27  aincluye privados, públicos urbanos e interurb...        0       1157870
28  bincluye remolques, ambulancias, motocargas y ...        0       1157870
29  Fuente: Registros administrativos, Dirección G...        0       1157870

    Autobuses    Jeep   Carga  Motocicletas  Volteo  Máquinas_Pesadas  Otrosb  \
25     139043  736171  548382             0       0             28324   25315
26     139043  736171  548382             0       0             28324   25315
27     139043  736171  548382             0       0             28324   25315
28     139043  736171  548382             0       0             28324   25315
29     139043  736171  548382             0       0             28324   25315

    Automóvilesa2  Autobuses2  Jeep2  Carga2  Motocicletas2  Volteo2  \
25             18         NaN    NaN     NaN            NaN      NaN
26             18         NaN    NaN     NaN            NaN      NaN
27             18         NaN    NaN     NaN            NaN      NaN
28             18         NaN    NaN     NaN            NaN      NaN
29             18         NaN    NaN     NaN            NaN      NaN

    Máquinas_Pesadas2  Otrosb2
25                NaN      NaN
26                NaN      NaN
27                NaN      NaN
28                NaN      NaN
29                NaN      NaN

In [4]:
# Data Cleaning
print("=" * 60)
print("DATA CLEANING PROCESS")
print("=" * 60)

# 1. Remove footer rows (keep only data rows 0-24)
df_clean = df[df['año'].apply(lambda x: isinstance(x, int) or (isinstance(x, str) and x.isdigit()))].copy()
print(f"\n1. Removed footer rows")
print(f"   New shape: {df_clean.shape}")

# 2. Rename 'column2' to 'Total_Vehiculos'
df_clean = df_clean.rename(columns={'column2': 'Total_Vehiculos'})
print(f"\n2. Renamed 'column2' to 'Total_Vehiculos'")

# 3. Convert 'año' to integer
df_clean['año'] = df_clean['año'].astype(int)

# 4. Identify counts and percentage columns
count_cols = ['Total_Vehiculos', 'Automóvilesa', 'Autobuses', 'Jeep', 'Carga', 
              'Motocicletas', 'Volteo', 'Máquinas_Pesadas', 'Otrosb']
pct_cols = ['Automóvilesa2', 'Autobuses2', 'Jeep2', 'Carga2', 
            'Motocicletas2', 'Volteo2', 'Máquinas_Pesadas2', 'Otrosb2']

# Convert count columns to int
for col in count_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce').astype('Int64')

# Convert percentage columns to float
for col in pct_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

print(f"\n3. Converted data types")
print(f"   - Count columns to integer")
print(f"   - Percentage columns to float")

# 5. Check for missing values
print(f"\n4. Missing values:")
missing = df_clean.isnull().sum()
print(missing[missing > 0])

# 6. Display cleaned data summary
print(f"\n5. Cleaned dataset summary:")
print(f"   Shape: {df_clean.shape}")
print(f"   Year range: {df_clean['año'].min()} - {df_clean['año'].max()}")
print(f"\nFirst few rows of cleaned data:")
print(df_clean.head())
print(f"\nLast few rows of cleaned data:")
print(df_clean.tail())
print(f"\nData types:")
print(df_clean.dtypes)

============================================================
DATA CLEANING PROCESS
============================================================

1. Removed footer rows
   New shape: (25, 18)

2. Renamed 'column2' to 'Total_Vehiculos'

3. Converted data types
   - Count columns to integer
   - Percentage columns to float

4. Missing values:
Series([], dtype: int64)

5. Cleaned dataset summary:
   Shape: (25, 18)
   Year range: 2000 - 2024

First few rows of cleaned data:
    año  Total_Vehiculos  Automóvilesa  Autobuses    Jeep   Carga  \
0  2000          1631006        511171      47806   79676  231306
1  2001          1689875        524980      49174   92374  241245
2  2002          1754612        537272      52396  103000  251786
3  2003          1804346        545275      55176  109008  259484
4  2004          1827873        547291      55328  111260  261281

   Motocicletas  Volteo  Máquinas_Pesadas  Otrosb  Automóvilesa2  Autobuses2  \
0        728964   10817             12066    9200             31         2.9
1        748543   11389             12664    9506             31         2.9
2        774951   12187             13201    9819             30         3.0
3        799154   12859             13380   10010             30         3.1
4        816298   12871             13445   10099             29         3.0

   Jeep2  Carga2  Motocicletas2  Volteo2  Máquinas_Pesadas2  Otrosb2
0    4.9    14.2      44.700001      0.7                0.7      0.6
1    5.5    14.3      44.299999      0.7                0.7      0.6
2    5.9    14.3      44.200001      0.7                0.8      0.6
3    6.0    14.4      44.299999      0.7                0.7      0.6
4    6.1    14.3      44.700001      0.7                0.7      0.6

Last few rows of cleaned data:
     año  Total_Vehiculos  Automóvilesa  Autobuses    Jeep   Carga  \
20  2020          4880507       1009594     113429  529410  461765
21  2021          5182036       1056769     118675  579539  479426
22  2022          5466120       1085591     123535  621617  497379
23  2023          5809136       1121695     130634  678031  521067
24  2024          6194052       1157870     139043  736171  548382

    Motocicletas  Volteo  Máquinas_Pesadas  Otrosb  Automóvilesa2  Autobuses2  \
20       2700402   21770             24616   19521             20         2.3
21       2878713   22610             25643   20661             20         2.3
22       3065065   23955             26541   22437             19         2.3
23       3280646   25534             27567   23962             19         2.2
24       3531967   26980             28324   25315             18         2.2

    Jeep2  Carga2  Motocicletas2  Volteo2  Máquinas_Pesadas2  Otrosb2
20   10.8     9.5      55.299999      0.4                0.5      0.4
21   11.2     9.3      55.599998      0.4                0.5      0.4
22   11.4     9.1      56.099998      0.4                0.5      0.4
23   11.7     9.0      56.500000      0.4                0.5      0.4
24   11.9     8.9      57.000000      0.4                0.5      0.4

Data types:
año                    int64
Total_Vehiculos        Int64
Automóvilesa           Int64
Autobuses              Int64
Jeep                   Int64
Carga                  Int64
Motocicletas           Int64
Volteo                 Int64
Máquinas_Pesadas       Int64
Otrosb                 Int64
Automóvilesa2          int64
Autobuses2           float64
Jeep2                float64
Carga2               float64
Motocicletas2        float64
Volteo2              float64
Máquinas_Pesadas2    float64
Otrosb2              float64
dtype: object

In [5]:
# Separate counts and percentages into distinct dataframes
print("\n" + "=" * 60)
print("REORGANIZING DATA")
print("=" * 60)

# Count dataframe (absolute numbers)
df_counts = df_clean[['año', 'Total_Vehiculos', 'Automóvilesa', 'Autobuses', 'Jeep', 
                       'Carga', 'Motocicletas', 'Volteo', 'Máquinas_Pesadas', 'Otrosb']].copy()

# Rename columns for percentages (remove '2' suffix and interpret as percentages)
df_pct = df_clean[['año', 'Automóvilesa2', 'Autobuses2', 'Jeep2', 'Carga2', 
                    'Motocicletas2', 'Volteo2', 'Máquinas_Pesadas2', 'Otrosb2']].copy()

df_pct.columns = ['año', 'Automóviles_%', 'Autobuses_%', 'Jeep_%', 'Carga_%', 
                  'Motocicletas_%', 'Volteo_%', 'Máquinas_Pesadas_%', 'Otros_%']

print("\n✓ Created df_counts - Vehicle counts by type")
print(f"  Shape: {df_counts.shape}")
print(f"  Columns: {list(df_counts.columns)}")

print("\n✓ Created df_pct - Percentage distribution by vehicle type")
print(f"  Shape: {df_pct.shape}")
print(f"  Columns: {list(df_pct.columns)}")

# Basic statistics
print("\n" + "=" * 60)
print("BASIC STATISTICS")
print("=" * 60)

print("\nTotal vehicles by year:")
print(df_counts[['año', 'Total_Vehiculos']])

print("\nVehicle type counts (2024):")
vehicle_2024 = df_counts[df_counts['año'] == 2024].iloc[0, 2:]
print(vehicle_2024.sort_values(ascending=False))

print(f"\nClean datasets ready for analysis!")
print(f"- df_clean: Full cleaned dataset with both counts and percentages")
print(f"- df_counts: Vehicle counts by type and year")
print(f"- df_pct: Percentage distribution by vehicle type and year")

============================================================
REORGANIZING DATA
============================================================

✓ Created df_counts - Vehicle counts by type
  Shape: (25, 10)
  Columns: ['año', 'Total_Vehiculos', 'Automóvilesa', 'Autobuses', 'Jeep', 'Carga', 'Motocicletas', 'Volteo', 'Máquinas_Pesadas', 'Otrosb']

✓ Created df_pct - Percentage distribution by vehicle type
  Shape: (25, 9)
  Columns: ['año', 'Automóviles_%', 'Autobuses_%', 'Jeep_%', 'Carga_%', 'Motocicletas_%', 'Volteo_%', 'Máquinas_Pesadas_%', 'Otros_%']

============================================================
BASIC STATISTICS
============================================================

Total vehicles by year:
     año  Total_Vehiculos
0   2000          1631006
1   2001          1689875
2   2002          1754612
3   2003          1804346
4   2004          1827873
5   2005          1887576
6   2006          2081572
7   2007          2294309
8   2008          2514881
9   2009          2658668
10  2010          2815189
11  2011          2953601
12  2012          3089835
13  2013          3244059
14  2014          3413858
15  2015          3631907
16  2016          3883068
17  2017          4125701
18  2018          4384984
19  2019          4668584
20  2020          4880507
21  2021          5182036
22  2022          5466120
23  2023          5809136
24  2024          6194052

Vehicle type counts (2024):
Motocicletas        3531967
Automóvilesa        1157870
Jeep                 736171
Carga                548382
Autobuses            139043
Máquinas_Pesadas      28324
Volteo                26980
Otrosb                25315
Name: 24, dtype: Int64

Clean datasets ready for analysis!
- df_clean: Full cleaned dataset with both counts and percentages
- df_counts: Vehicle counts by type and year
- df_pct: Percentage distribution by vehicle type and year

In [17]:
# 3. Eliminar columnas que no usaremos o duplicadas de porcentaje crudo
# Nos quedamos con los valores absolutos (las primeras columnas)
columnas_interes = [
    'año', 'Automóvilesa', 'Autobuses', 'Jeep', 
    'Carga', 'Motocicletas', 'Volteo', 'Máquinas_Pesadas', 'Otrosb'
]
df_clean = df_clean[columnas_interes]
df_clean

,año,Automóvilesa,Autobuses,Jeep,Carga,Motocicletas,Volteo,Máquinas_Pesadas,Otrosb
0,2000,511171,47806,79676,231306,728964,10817,12066,9200
1,2001,524980,49174,92374,241245,748543,11389,12664,9506
2,2002,537272,52396,103000,251786,774951,12187,13201,9819
3,2003,545275,55176,109008,259484,799154,12859,13380,10010
4,2004,547291,55328,111260,261281,816298,12871,13445,10099
5,2005,553333,55757,118399,268487,854459,13420,13554,10167
6,2006,576952,59763,148755,287390,968455,14431,15036,10790
7,2007,602722,63518,178725,303946,1101883,15957,16166,11392
8,2008,632382,68201,210157,322620,1234898,17239,17331,12053
9,2009,647655,71146,232160,333467,1325993,17696,17914,12637
10,2010,665155,74800,257593,345552,1421748,18511,18655,13175
11,2011,682287,77728,278870,356595,1506214,18904,19269,13734
12,2012,701157,80661,297542,365429,1591961,19099,19719,14267
13,2013,723505,82844,315769,374052,1693592,19307,20293,14697
14,2014,748289,85498,336564,382738,1805387,19513,20737,15132
15,2015,783839,89062,362879,393652,1945941,19689,21212,15633
16,2016,831407,93316,395418,407318,2097556,20071,21799,16183
17,2017,878724,97570,426659,420555,2242360,20388,22648,16797
18,2018,925614,102404,459456,434028,2401557,20895,23491,17539
19,2019,971484,108497,497677,449553,2577135,21322,24150,18766
20,2020,1009594,113429,529410,461765,2700402,21770,24616,19521
21,2021,1056769,118675,579539,479426,2878713,22610,25643,20661
22,2022,1085591,123535,621617,497379,3065065,23955,26541,22437
23,2023,1121695,130634,678031,521067,3280646,25534,27567,23962
24,2024,1157870,139043,736171,548382,3531967,26980,28324,25315
25,*Cifras sujetas a rectifiación,1157870,139043,736171,548382,0,0,28324,25315
26,Nota: El parque vehicular se refiere al stock ...,1157870,139043,736171,548382,0,0,28324,25315
27,"aincluye privados, públicos urbanos e interurb...",1157870,139043,736171,548382,0,0,28324,25315
28,"bincluye remolques, ambulancias, motocargas y ...",1157870,139043,736171,548382,0,0,28324,25315
29,"Fuente: Registros administrativos, Dirección G...",1157870,139043,736171,548382,0,0,28324,25315

In [18]:
#  Guardar el nuevo archivo limpio
df_clean.to_csv("vehiculos_limpios.csv", index=False)
print("¡Datos procesados y guardados con éxito en 'vehiculos_limpios.csv'!")
df_clean.head()

¡Datos procesados y guardados con éxito en 'vehiculos_limpios.csv'!

,año,Automóvilesa,Autobuses,Jeep,Carga,Motocicletas,Volteo,Máquinas_Pesadas,Otrosb
0,2000,511171,47806,79676,231306,728964,10817,12066,9200
1,2001,524980,49174,92374,241245,748543,11389,12664,9506
2,2002,537272,52396,103000,251786,774951,12187,13201,9819
3,2003,545275,55176,109008,259484,799154,12859,13380,10010
4,2004,547291,55328,111260,261281,816298,12871,13445,10099