In [1]:
try:
   import pandas as pd
except ModuleNotFoundError:
   import sys, subprocess
   subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas"])
   import pandas as pd

import pyodbc

# 1. Configurar la conexión
server = 'JUNIORPC\\SQLEXPRESS'      # Cambia por el nombre de tu servidor
database = 'Parquevehicular'  # Cambia por tu base de datos

conn_str = f'Driver={{ODBC Driver 18 for SQL Server}};Server={server};Database={database};Trusted_Connection=yes;TrustServerCertificate=yes;'
conexion = pyodbc.connect(conn_str)

# 2. Escribir la consulta SQL eligiendo solo las columnas deseadas
query = """
   SELECT TOP (1000) [año]
     ,[column2]
     ,[Automóvilesa]
     ,[Autobuses]
     ,[Jeep]
     ,[Carga]
     ,[Motocicletas]
     ,[Volteo]
     ,[Máquinas_Pesadas]
     ,[Otrosb]
     ,[Automóvilesa2]
     ,[Autobuses2]
     ,[Jeep2]
     ,[Carga2]
     ,[Motocicletas2]
     ,[Volteo2]
     ,[Máquinas_Pesadas2]
     ,[Otrosb2]
  FROM [Parquevehicular].[dbo].[3-10-11-parque-vehicular-año-según-tipo(3.10]
"""

# 3. Importar los datos directamente a Python
df = pd.read_sql(query, conexion)

# Cerrar la conexión base
conexion.close()

# Mostrar las primeras filas en Python
print(df.head())
import pyodbc

# 1. Configurar la conexión
server = 'JUNIORPC\\SQLEXPRESS'      # Cambia por el nombre de tu servidor
database = 'Parquevehicular'  # Cambia por tu base de datos

conn_str = f'Driver={{ODBC Driver 18 for SQL Server}};Server={server};Database={database};Trusted_Connection=yes;' "TrustServerCertificate=yes;" 
conexion = pyodbc.connect(conn_str)

# 2. Escribir la consulta SQL eligiendo solo las columnas deseadas
query = """
   SELECT TOP (1000) [año]
      ,[column2]
      ,[Automóvilesa]
      ,[Autobuses]
      ,[Jeep]
      ,[Carga]
      ,[Motocicletas]
      ,[Volteo]
      ,[Máquinas_Pesadas]
      ,[Otrosb]
      ,[Automóvilesa2]
      ,[Autobuses2]
      ,[Jeep2]
      ,[Carga2]
      ,[Motocicletas2]
      ,[Volteo2]
      ,[Máquinas_Pesadas2]
      ,[Otrosb2]
  FROM [Parquevehicular].[dbo].[3-10-11-parque-vehicular-año-según-tipo(3.10]
"""

# 3. Importar los datos directamente a Python
df = pd.read_sql(query, conexion)

# Cerrar la conexión base
conexion.close()

# Mostrar las primeras filas en Python
print(df.head())

C:\Users\JUNIO\AppData\Local\Temp\ipykernel_7220\3411288592.py:41: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexion)

    año    column2  Automóvilesa  Autobuses      Jeep     Carga  Motocicletas  \
0  2000  1631006.0      511171.0    47806.0   79676.0  231306.0      728964.0
1  2001  1689875.0      524980.0    49174.0   92374.0  241245.0      748543.0
2  2002  1754612.0      537272.0    52396.0  103000.0  251786.0      774951.0
3  2003  1804346.0      545275.0    55176.0  109008.0  259484.0      799154.0
4  2004  1827873.0      547291.0    55328.0  111260.0  261281.0      816298.0

    Volteo  Máquinas_Pesadas   Otrosb  Automóvilesa2  Autobuses2  Jeep2  \
0  10817.0           12066.0   9200.0      31.299999         2.9    4.9
1  11389.0           12664.0   9506.0      31.100000         2.9    5.5
2  12187.0           13201.0   9819.0      30.600000         3.0    5.9
3  12859.0           13380.0  10010.0      30.200001         3.1    6.0
4  12871.0           13445.0  10099.0      29.900000         3.0    6.1

   Carga2  Motocicletas2  Volteo2  Máquinas_Pesadas2  Otrosb2
0    14.2      44.700001      0.7                0.7      0.6
1    14.3      44.299999      0.7                0.7      0.6
2    14.3      44.200001      0.7                0.8      0.6
3    14.4      44.299999      0.7                0.7      0.6
4    14.3      44.700001      0.7                0.7      0.6

C:\Users\JUNIO\AppData\Local\Temp\ipykernel_7220\3411288592.py:81: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexion)

    año    column2  Automóvilesa  Autobuses      Jeep     Carga  Motocicletas  \
0  2000  1631006.0      511171.0    47806.0   79676.0  231306.0      728964.0
1  2001  1689875.0      524980.0    49174.0   92374.0  241245.0      748543.0
2  2002  1754612.0      537272.0    52396.0  103000.0  251786.0      774951.0
3  2003  1804346.0      545275.0    55176.0  109008.0  259484.0      799154.0
4  2004  1827873.0      547291.0    55328.0  111260.0  261281.0      816298.0

    Volteo  Máquinas_Pesadas   Otrosb  Automóvilesa2  Autobuses2  Jeep2  \
0  10817.0           12066.0   9200.0      31.299999         2.9    4.9
1  11389.0           12664.0   9506.0      31.100000         2.9    5.5
2  12187.0           13201.0   9819.0      30.600000         3.0    5.9
3  12859.0           13380.0  10010.0      30.200001         3.1    6.0
4  12871.0           13445.0  10099.0      29.900000         3.0    6.1

   Carga2  Motocicletas2  Volteo2  Máquinas_Pesadas2  Otrosb2
0    14.2      44.700001      0.7                0.7      0.6
1    14.3      44.299999      0.7                0.7      0.6
2    14.3      44.200001      0.7                0.8      0.6
3    14.4      44.299999      0.7                0.7      0.6
4    14.3      44.700001      0.7                0.7      0.6

In [2]:
df = df.convert_dtypes()# Convertir los tipos de datos a los más adecuados

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   año                30 non-null     string
 1   column2            25 non-null     Int64
 2   Automóvilesa       25 non-null     Int64
 3   Autobuses          25 non-null     Int64
 4   Jeep               25 non-null     Int64
 5   Carga              25 non-null     Int64
 6   Motocicletas       25 non-null     Int64
 7   Volteo             25 non-null     Int64
 8   Máquinas_Pesadas   25 non-null     Int64
 9   Otrosb             25 non-null     Int64
 10  Automóvilesa2      25 non-null     Float64
 11  Autobuses2         25 non-null     Float64
 12  Jeep2              25 non-null     Float64
 13  Carga2             25 non-null     Float64
 14  Motocicletas2      25 non-null     Float64
 15  Volteo2            25 non-null     Float64
 16  Máquinas_Pesadas2  25 non-null     Float64
 17  Otrosb2            25 non-null     Float64
dtypes: Float64(8), Int64(9), string(1)
memory usage: 4.8 KB

In [4]:
df.describe()

,column2,Automóvilesa,Autobuses,Jeep,Carga,Motocicletas,Volteo,Máquinas_Pesadas,Otrosb,Automóvilesa2,Autobuses2,Jeep2,Carga2,Motocicletas2,Volteo2,Máquinas_Pesadas2,Otrosb2
count,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0
mean,3355494.2,760880.52,83838.44,326268.36,367940.12,1763753.68,18296.56,19576.84,14939.68,24.188,2.608,8.928,11.748,50.864,0.584,0.62,0.476
std,1408499.750987,208700.0829,27082.698792,197204.074119,92637.882241,870319.199691,4401.999092,5018.035968,4715.287785,4.119701,0.284195,2.135127,1.978872,4.464478,0.121381,0.095743,0.077889
min,1631006.0,511171.0,47806.0,79676.0,231306.0,728964.0,10817.0,12066.0,9200.0,18.700001,2.2,4.9,8.9,44.200001,0.4,0.5,0.4
25%,2081572.0,576952.0,59763.0,148755.0,287390.0,968455.0,14431.0,15036.0,10790.0,21.1,2.3,7.1,9.9,46.5,0.5,0.5,0.4
50%,3089835.0,701157.0,80661.0,297542.0,365429.0,1591961.0,19099.0,19719.0,14267.0,22.700001,2.6,9.6,11.8,51.5,0.6,0.6,0.5
75%,4384984.0,925614.0,102404.0,459456.0,434028.0,2401557.0,20895.0,23491.0,17539.0,27.700001,2.9,10.5,13.8,54.799999,0.7,0.7,0.5
max,6194052.0,1157870.0,139043.0,736171.0,548382.0,3531967.0,26980.0,28324.0,25315.0,31.299999,3.1,11.9,14.4,57.0,0.7,0.8,0.6

In [5]:
df.isnull().sum()

año                  0
column2              5
Automóvilesa         5
Autobuses            5
Jeep                 5
Carga                5
Motocicletas         5
Volteo               5
Máquinas_Pesadas     5
Otrosb               5
Automóvilesa2        5
Autobuses2           5
Jeep2                5
Carga2               5
Motocicletas2        5
Volteo2              5
Máquinas_Pesadas2    5
Otrosb2              5
dtype: int64

In [6]:
df['Automóvilesa'] = df['Automóvilesa'].fillna(method='ffill')  # Rellenar con el valor anterior
df['Autobuses'] = df['Autobuses'].fillna(method='ffill')  # Rellenar con el valor anterior
df['Jeep'] = df['Jeep'].fillna(method='ffill')  # Rellenar con el valor anterior
df['Carga'] = df['Carga'].fillna(method='ffill')  # Rellenar con el valor anterior
# Reemplaza los nulos con 0 y luego convierte a entero
df['Motocicletas'] = df['Motocicletas'].fillna(0).astype(int) # Rellenar con 0 y convertir a entero a los valors nulos NaN None NA

df['Volteo'] = df['Volteo'].fillna(0).astype(int)  # Rellenar con 0 y convertir a entero
df['Máquinas_Pesadas'] = df['Máquinas_Pesadas'].fillna(method='ffill')
df['Otrosb'] = df['Otrosb'].fillna(method='ffill')
df['Automóvilesa2'] = df['Automóvilesa2'].fillna(method='ffill') 
df['column2'] = df['column2'].fillna(0).astype(int)     #  Eliminar la columna 'column2' si no es relevante

C:\Users\JUNIO\AppData\Local\Temp\ipykernel_7220\966446367.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Automóvilesa'] = df['Automóvilesa'].fillna(method='ffill')  # Rellenar con el valor anterior
C:\Users\JUNIO\AppData\Local\Temp\ipykernel_7220\966446367.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Autobuses'] = df['Autobuses'].fillna(method='ffill')  # Rellenar con el valor anterior
C:\Users\JUNIO\AppData\Local\Temp\ipykernel_7220\966446367.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Jeep'] = df['Jeep'].fillna(method='ffill')  # Rellenar con el valor anterior
C:\Users\JUNIO\AppData\Local\Temp\ipykernel_7220\966446367.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Carga'] = df['Carga'].fillna(method='ffill')  # Rellenar con el valor anterior
C:\Users\JUNIO\AppData\Local\Temp\ipykernel_7220\966446367.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Máquinas_Pesadas'] = df['Máquinas_Pesadas'].fillna(method='ffill')
C:\Users\JUNIO\AppData\Local\Temp\ipykernel_7220\966446367.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Otrosb'] = df['Otrosb'].fillna(method='ffill')
C:\Users\JUNIO\AppData\Local\Temp\ipykernel_7220\966446367.py:11: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Automóvilesa2'] = df['Automóvilesa2'].fillna(method='ffill')

In [7]:
df.isnull().sum()

año                  0
column2              0
Automóvilesa         0
Autobuses            0
Jeep                 0
Carga                0
Motocicletas         0
Volteo               0
Máquinas_Pesadas     0
Otrosb               0
Automóvilesa2        0
Autobuses2           5
Jeep2                5
Carga2               5
Motocicletas2        5
Volteo2              5
Máquinas_Pesadas2    5
Otrosb2              5
dtype: int64

In [8]:
df.dtypes # Verificar los tipos de datos de cada columna

año                  string[python]
column2                       int64
Automóvilesa                  Int64
Autobuses                     Int64
Jeep                          Int64
Carga                         Int64
Motocicletas                  int64
Volteo                        int64
Máquinas_Pesadas              Int64
Otrosb                        Int64
Automóvilesa2               Float64
Autobuses2                  Float64
Jeep2                       Float64
Carga2                      Float64
Motocicletas2               Float64
Volteo2                     Float64
Máquinas_Pesadas2           Float64
Otrosb2                     Float64
dtype: object

In [9]:
df = df.astype({'Automóvilesa': 'int64', 'Autobuses': 'int64', 'Jeep': 'int64', 'Carga': 'int64', 
                'Motocicletas': 'int64', 'Volteo': 'int64', 'Máquinas_Pesadas': 'int64', 
                'Otrosb': 'int64', 'Automóvilesa2': 'int64'}) # Convertir a enteros

In [10]:
df

,año,column2,Automóvilesa,Autobuses,Jeep,Carga,Motocicletas,Volteo,Máquinas_Pesadas,Otrosb,Automóvilesa2,Autobuses2,Jeep2,Carga2,Motocicletas2,Volteo2,Máquinas_Pesadas2,Otrosb2
0,2000,1631006,511171,47806,79676,231306,728964,10817,12066,9200,31,2.9,4.9,14.2,44.700001,0.7,0.7,0.6
1,2001,1689875,524980,49174,92374,241245,748543,11389,12664,9506,31,2.9,5.5,14.3,44.299999,0.7,0.7,0.6
2,2002,1754612,537272,52396,103000,251786,774951,12187,13201,9819,30,3.0,5.9,14.3,44.200001,0.7,0.8,0.6
3,2003,1804346,545275,55176,109008,259484,799154,12859,13380,10010,30,3.1,6.0,14.4,44.299999,0.7,0.7,0.6
4,2004,1827873,547291,55328,111260,261281,816298,12871,13445,10099,29,3.0,6.1,14.3,44.700001,0.7,0.7,0.6
5,2005,1887576,553333,55757,118399,268487,854459,13420,13554,10167,29,3.0,6.3,14.2,45.299999,0.7,0.7,0.5
6,2006,2081572,576952,59763,148755,287390,968455,14431,15036,10790,27,2.9,7.1,13.8,46.5,0.7,0.7,0.5
7,2007,2294309,602722,63518,178725,303946,1101883,15957,16166,11392,26,2.8,7.8,13.2,48.0,0.7,0.7,0.5
8,2008,2514881,632382,68201,210157,322620,1234898,17239,17331,12053,25,2.7,8.4,12.8,49.099998,0.7,0.7,0.5
9,2009,2658668,647655,71146,232160,333467,1325993,17696,17914,12637,24,2.7,8.7,12.5,49.900002,0.7,0.7,0.5
10,2010,2815189,665155,74800,257593,345552,1421748,18511,18655,13175,23,2.7,9.2,12.3,50.5,0.7,0.7,0.5
11,2011,2953601,682287,77728,278870,356595,1506214,18904,19269,13734,23,2.6,9.4,12.1,51.0,0.6,0.7,0.5
12,2012,3089835,701157,80661,297542,365429,1591961,19099,19719,14267,22,2.6,9.6,11.8,51.5,0.6,0.6,0.5
13,2013,3244059,723505,82844,315769,374052,1693592,19307,20293,14697,22,2.6,9.7,11.5,52.200001,0.6,0.6,0.5
14,2014,3413858,748289,85498,336564,382738,1805387,19513,20737,15132,21,2.5,9.9,11.2,52.900002,0.6,0.6,0.4
15,2015,3631907,783839,89062,362879,393652,1945941,19689,21212,15633,21,2.5,10.0,10.8,53.599998,0.5,0.6,0.4
16,2016,3883068,831407,93316,395418,407318,2097556,20071,21799,16183,21,2.4,10.2,10.5,54.0,0.5,0.6,0.4
17,2017,4125701,878724,97570,426659,420555,2242360,20388,22648,16797,21,2.4,10.3,10.2,54.400002,0.5,0.5,0.4
18,2018,4384984,925614,102404,459456,434028,2401557,20895,23491,17539,21,2.3,10.5,9.9,54.799999,0.5,0.5,0.4
19,2019,4668584,971484,108497,497677,449553,2577135,21322,24150,18766,20,2.3,10.7,9.6,55.200001,0.5,0.5,0.4
20,2020,4880507,1009594,113429,529410,461765,2700402,21770,24616,19521,20,2.3,10.8,9.5,55.299999,0.4,0.5,0.4
21,2021,5182036,1056769,118675,579539,479426,2878713,22610,25643,20661,20,2.3,11.2,9.3,55.599998,0.4,0.5,0.4
22,2022,5466120,1085591,123535,621617,497379,3065065,23955,26541,22437,19,2.3,11.4,9.1,56.099998,0.4,0.5,0.4
23,2023,5809136,1121695,130634,678031,521067,3280646,25534,27567,23962,19,2.2,11.7,9.0,56.5,0.4,0.5,0.4
24,2024,6194052,1157870,139043,736171,548382,3531967,26980,28324,25315,18,2.2,11.9,8.9,57.0,0.4,0.5,0.4
25,*Cifras sujetas a rectifiación,0,1157870,139043,736171,548382,0,0,28324,25315,18,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
26,Nota: El parque vehicular se refiere al stock ...,0,1157870,139043,736171,548382,0,0,28324,25315,18,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
27,"aincluye privados, públicos urbanos e interurb...",0,1157870,139043,736171,548382,0,0,28324,25315,18,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
28,"bincluye remolques, ambulancias, motocargas y ...",0,1157870,139043,736171,548382,0,0,28324,25315,18,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
29,"Fuente: Registros administrativos, Dirección G...",0,1157870,139043,736171,548382,0,0,28324,25315,18,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [11]:
#vehiculos por año
df.groupby('año')[['Automóvilesa', 'Autobuses', 'Jeep', 'Carga', 'Motocicletas', 'Volteo', 'Máquinas_Pesadas', 'Otrosb', 'Automóvilesa2']].sum()

,Automóvilesa,Autobuses,Jeep,Carga,Motocicletas,Volteo,Máquinas_Pesadas,Otrosb,Automóvilesa2
año,,,,,,,,,
*Cifras sujetas a rectifiación,1157870,139043,736171,548382,0,0,28324,25315,18
2000,511171,47806,79676,231306,728964,10817,12066,9200,31
2001,524980,49174,92374,241245,748543,11389,12664,9506,31
2002,537272,52396,103000,251786,774951,12187,13201,9819,30
2003,545275,55176,109008,259484,799154,12859,13380,10010,30
2004,547291,55328,111260,261281,816298,12871,13445,10099,29
2005,553333,55757,118399,268487,854459,13420,13554,10167,29
2006,576952,59763,148755,287390,968455,14431,15036,10790,27
2007,602722,63518,178725,303946,1101883,15957,16166,11392,26
2008,632382,68201,210157,322620,1234898,17239,17331,12053,25
2009,647655,71146,232160,333467,1325993,17696,17914,12637,24
2010,665155,74800,257593,345552,1421748,18511,18655,13175,23
2011,682287,77728,278870,356595,1506214,18904,19269,13734,23
2012,701157,80661,297542,365429,1591961,19099,19719,14267,22
2013,723505,82844,315769,374052,1693592,19307,20293,14697,22
2014,748289,85498,336564,382738,1805387,19513,20737,15132,21
2015,783839,89062,362879,393652,1945941,19689,21212,15633,21
2016,831407,93316,395418,407318,2097556,20071,21799,16183,21
2017,878724,97570,426659,420555,2242360,20388,22648,16797,21
2018,925614,102404,459456,434028,2401557,20895,23491,17539,21
2019,971484,108497,497677,449553,2577135,21322,24150,18766,20
2020,1009594,113429,529410,461765,2700402,21770,24616,19521,20
2021,1056769,118675,579539,479426,2878713,22610,25643,20661,20
2022,1085591,123535,621617,497379,3065065,23955,26541,22437,19
2023,1121695,130634,678031,521067,3280646,25534,27567,23962,19
2024,1157870,139043,736171,548382,3531967,26980,28324,25315,18
"Fuente: Registros administrativos, Dirección General de Impuestos Internos (DGII)",1157870,139043,736171,548382,0,0,28324,25315,18
Nota: El parque vehicular se refiere al stock de vehículos en el país al 31 de diciembre de cada año.,1157870,139043,736171,548382,0,0,28324,25315,18
"aincluye privados, públicos urbanos e interurbanos.",1157870,139043,736171,548382,0,0,28324,25315,18
"bincluye remolques, ambulancias, motocargas y fúnebres",1157870,139043,736171,548382,0,0,28324,25315,18

In [12]:
# guardar el dataframe limpio en un nuevo archivo CSV
df.to_csv('parque_vehicular_limpio.csv', index=False)